### ISSUE TITLE
Cannot get element child

### ISSUE THREAD

**Issue by viperscape** [Florob/RustyXML#14]
I am noticing an issue parsing this [xml](https://www.refheap.com/102062)

Where this works:
``` rust
fn parse_next_path (e: &Element) {
    for ec in e.children.iter() {
        match ec {
            &Xml::ElementNode(ref ecc) => println!("{:?}",ecc), // Element { name: "path", ... }
            _ => (),
        }
    }
}
```

but this does not: ```println!("{:?}",e.get_child("path", None));```

where [e](https://www.refheap.com/102063) is: ```println!("{:?}",e);```

I'm using it as such:
``` rust
fn test_svg () {
    let v = load_svg("assets/rust-logo-blk.svg");
    parse_next_path(&v[0]);
}


fn load_svg (path: &str) -> Vec<Element> {
    let mut p = xml::Parser::new();
    let mut eb = xml::ElementBuilder::new();

    let mut f = match File::open(path) {
        Ok(file) => file,
        Err(err) => { println!("fail: load file");
                      panic!(err) },
    };
    
    let mut c = String::new();
    if let Err(err) = f.read_to_string(&mut c) {
        println!("fail: read file");
        panic!(err);
    };
    
    p.feed_str(&c);
    let mut ve = vec!();
    for e in p.filter_map(|x| eb.handle_event(x)) {
        if let Ok(_e) = e {
            ve.push(_e);
        }
    }

    ve
}
```

Any idea what I am doing wrong?

**Comment by Florob** [comment]
Your `get_child()` call is not requesting what you want. `e.get_child("path", None)` looks for a path element, without a defined namespace. The path element in your SVG is in the default namespace `http://www.w3.org/2000/svg` though. The correct invocation is `e.get_child("path", Some("http://www.w3.org/2000/svg"))`.

**Comment by viperscape** [comment]
Ah, good to know! I didn't realize it was required for this file, now I see it. Thanks!

**Comment by viperscape** [comment]
Also, it would be ideal if default_ns was stored as Option<&str> for convenience when calling [get_child](https://github.com/Florob/RustyXML/blob/master/src/element.rs#L181), or a get_ns(&self) -> Option<&str> method was available
Thanks again!
