### ISSUE TITLE
Attribute order is non-deterministic

### ISSUE THREAD

**Issue by julianandrews** [Florob/RustyXML#19]
Right now the attributes in an `Element` are stored in a `HashMap` and when you write out the XML as a string their order is potentially different each time.

This is problematic because:

- it means the generated string is unstable (which is a nuisance if you're trying to write reproducible tests), and
- it makes it impossible to control the output order (which may be useful for human readable XML files).

In my case, I'm running into both issues. I'm using XML output for some integration tests, and I need the files to be produced consistently, and I also would like the output to be human readable with the attributes in a sensible order and related attributes together.

Ideally the attributes would be stored in some sort of map that preserved insertion order (like [indexmap](https://crates.io/crates/indexmap)), and output would be deterministic.

**Comment by julianandrews** [comment]
I would note that just changing the order of the attribute output to be deterministic would fix the bigger problem (non-deterministic output). I think `minidom` sorts attributes alphabetically which seems like a reasonable choice.

I'd advocate for maintaining insertion order, but thought I'd mention this!

**Comment by Florob** [comment]
Admittedly this crate is mostly in maintenance mode.
This seems easy enough to implement using `indexmap` though. It will probably end up behind a feature gate, so RustyXML remains dependency-free by default.
I'll try to push out a new release with this and some other cleanup over the weekend.
