### ISSUE TITLE
Push version to Crates.io?

### ISSUE THREAD

**Issue by frewsxcv** [Florob/RustyXML#9]
I love this library, thanks for the work you put into it :)

I'd like to be able to publish my library https://github.com/frewsxcv/rust-rss to crates.io, but am unable to since my library depends on this git repository (instead of an explicit rustyxml crates.io version). Have you considered publishing a version on crates.io?

**Comment by Florob** [comment]
I just published a first version to [crates.io](https://crates.io/crates/RustyXML), there were still some API changes. Feedback is very welcome.
